[project]
name = "agent-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai>=0.121.1",
    "crewai-tools>=0.45.0",
    "dotenv>=0.9.9",
    "openai>=1.75.0",
]
